"""add group_id to cameras and connection-code processor fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-03-18 18:30:00.000000
"""

from typing import Sequence, Union

from alembic import op


revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE cameras
        ADD COLUMN IF NOT EXISTS group_id INTEGER
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'cameras_group_id_fkey'
            ) THEN
                ALTER TABLE cameras
                ADD CONSTRAINT cameras_group_id_fkey
                FOREIGN KEY (group_id) REFERENCES groups(group_id) ON DELETE SET NULL;
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS cameras_group_idx ON cameras(group_id)
        """
    )

    op.execute(
        """
        ALTER TABLE processors
        ADD COLUMN IF NOT EXISTS ip_address VARCHAR(45)
        """
    )
    op.execute(
        """
        ALTER TABLE processors
        ADD COLUMN IF NOT EXISTS os_info VARCHAR(255)
        """
    )
    op.execute(
        """
        ALTER TABLE processors
        ADD COLUMN IF NOT EXISTS version VARCHAR(50)
        """
    )
    op.execute(
        """
        ALTER TABLE processors
        ADD COLUMN IF NOT EXISTS last_metrics TEXT
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS processor_connection_codes (
            code_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code VARCHAR(20) UNIQUE NOT NULL,
            created_by_user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
            expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            used_at TIMESTAMP WITHOUT TIME ZONE NULL,
            used_by_processor_id INTEGER NULL REFERENCES processors(processor_id) ON DELETE SET NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS processor_connection_codes")
    op.execute("DROP INDEX IF EXISTS cameras_group_idx")
    op.execute("ALTER TABLE processors DROP COLUMN IF EXISTS last_metrics")
    op.execute("ALTER TABLE processors DROP COLUMN IF EXISTS version")
    op.execute("ALTER TABLE processors DROP COLUMN IF EXISTS os_info")
    op.execute("ALTER TABLE processors DROP COLUMN IF EXISTS ip_address")
    op.execute("ALTER TABLE cameras DROP CONSTRAINT IF EXISTS cameras_group_id_fkey")
    op.execute("ALTER TABLE cameras DROP COLUMN IF EXISTS group_id")
