[platformio]
default_envs = esp32_s3_n16r8

[env:esp32_s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
extra_scripts = pre:scripts/inject_config.py
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM

[env:node1]
extends = env:esp32_s3_n16r8
build_flags =
  ${env:esp32_s3_n16r8.build_flags}
  -DNODE_NUM_ID=1
  -DNODE_TDM_SLOT=0

[env:node2]
extends = env:esp32_s3_n16r8
build_flags =
  ${env:esp32_s3_n16r8.build_flags}
  -DNODE_NUM_ID=2
  -DNODE_TDM_SLOT=1

[env:node3]
extends = env:esp32_s3_n16r8
build_flags =
  ${env:esp32_s3_n16r8.build_flags}
  -DNODE_NUM_ID=3
  -DNODE_TDM_SLOT=2

[env:node4]
extends = env:esp32_s3_n16r8
build_flags =
  ${env:esp32_s3_n16r8.build_flags}
  -DNODE_NUM_ID=4
  -DNODE_TDM_SLOT=3

[env:node5]
extends = env:esp32_s3_n16r8
build_flags =
  ${env:esp32_s3_n16r8.build_flags}
  -DNODE_NUM_ID=5
  -DNODE_TDM_SLOT=4

[env:node6]
extends = env:esp32_s3_n16r8
build_flags =
  ${env:esp32_s3_n16r8.build_flags}
  -DNODE_NUM_ID=6
  -DNODE_TDM_SLOT=5
